### ISSUE TITLE
Move the values for the TOKENS into a secrets file

### ISSUE THREAD

**Issue by robertjahn** [keptn-contrib/notification-service#18]
Move these values that are now in `notification-service.yaml`  into a k8 secrets file will make them more secure.   So change code and instructions in readme.
```
        env:
        - name: TEAMS_URL
          value: ""
        - name: BRIDGE_URL
          value: ""
        - name: SLACK_URL
          value: ""
        - name: WEBEXTEAMS_URL
          value: ""
```

Plus you can have the benefit of deploying the service without having to clone the repo, for example `kubectl apply -f https://raw.githubusercontent.com/keptn-contrib/notification-service/master/deploy/notification-service.yaml`
