### ISSUE TITLE
Make notification channels configurable by project, stage or service

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/notification-service#27]
Right now every message will be sent to the same Notification Channel, e.g: the same Slack Channel for all messages on that Keptn installation.

In real life we will however have different channels for a Keptn Project, Stage and Service. I therefore suggest we introduce a configuration file for the notification service that can be placed on project, stage or service level. That file can be used to specify the actual notification channel to send the notification to.

Example:
`notification/notification.conf.yaml`
```
notifications:
- slack:
  channel: https://myslack/quality-gate-project1
  events: evaluation-done
- slack:
  channel: https://myslack/approvals
  events: approvale-request
```
